// Configuration
 @fhirUrl = http://localhost:5826/fhir/r4
#@fhirUrl = http://server.fire.ly/r4
@endpoint = http://localhost:5826/fhir/r4/$subscription-hook
@topic = http://example.org/FHIR/SubscriptionTopic/encounter-complete

# @contentLevel = empty
@contentLevel = id-only
# @contentLevel = full-resource

@format = application/fhir+json
#@format = application/fhir+xml


### GET CapabilityStatement
GET {{fhirUrl}}/metadata
Accept: {{format}}
# Forwarded: host=ginoc.io;proto=https


### GET-based search for Patients
GET {{fhirUrl}}/$
Accept: {{format}}


### GET-based search for Patients
GET {{fhirUrl}}/Encounter
  ?patient.family:exact=Chalmers
Accept: {{format}}

### 
GET {{fhirUrl}}/Encounter
  ?_include=Encounter:patient
  &_include=Encounter:diagnosis
Accept: {{format}}

### 
GET {{fhirUrl}}/Patient
  ?given=Amy
  &family=S
Accept: {{format}}

### 
GET {{fhirUrl}}/Patient
  ?_revinclude=Encounter:patient
Accept: {{format}}

### GET SP
GET {{fhirUrl}}/SearchParameter
Accept: application/fhir+json
Accept: {{format}}

### POST Patient Contact Family Name SP
POST {{fhirUrl}}/SearchParameter
Content-Type: application/fhir+json
Accept: {{format}}

<@ ./sp-patient-contact-family.json

### 
GET {{fhirUrl}}/Patient
  ?contact-family=du
Accept: {{format}}

### POST Patient
POST {{fhirUrl}}/Patient
Content-Type: application/fhir+json
Accept: {{format}}

<@ ./patient-no-id.json

### POST Subscription
# @name postRestHookSubscription
POST {{fhirUrl}}/Subscription
Accept: {{format}}
Content-Type: application/fhir+json

{
  "resourceType": "Subscription",
  "status": "requested",
  "reason": "Test subscription",
  "criteria": "{{topic}}",
  "_criteria": {
      "extension": [
          {
              "url": "http://hl7.org/fhir/uv/subscriptions-backport/StructureDefinition/backport-filter-criteria",
              "valueString": "Encounter?patient=Patient/example"
          }
      ]
  },
  "channel": {
      "extension": [
          {
              "url": "http://hl7.org/fhir/uv/subscriptions-backport/StructureDefinition/backport-heartbeat-period",
              "valueUnsignedInt": 86400
          },
          {
              "url": "http://hl7.org/fhir/uv/subscriptions-backport/StructureDefinition/backport-timeout",
              "valueUnsignedInt": 60
          },
          {
              "url": "http://hl7.org/fhir/uv/subscriptions-backport/StructureDefinition/backport-max-count",
              "valuePositiveInt": 20
          }
      ],
      "type": "rest-hook",
      "endpoint": "{{endpoint}}",
      "payload": "{{format}}",
      "_payload": {
          "extension": [
              {
                  "url": "http://hl7.org/fhir/uv/subscriptions-backport/StructureDefinition/backport-payload-content",
                  "valueCode": "{{contentLevel}}"
              }
          ]
      }
  }
}

### GET SubscriptionStatus
GET {{fhirUrl}}/Subscription/{{postRestHookSubscription.response.body.$.id}}/$status
Accept: {{format}}

### GET SubscriptionEvents
GET {{fhirUrl}}/Subscription/{{postRestHookSubscription.response.body.$.id}}/$events?content={{contentLevel}}
Accept: {{format}}


### POST finished Encounter
# @name postCompleteEncounter
POST {{fhirUrl}}/Encounter
Accept: {{format}}
Content-Type: application/fhir+json

{
  "resourceType": "Encounter",
  "status": "finished",
  "class": {
    "system": "http://terminology.hl7.org/CodeSystem/v3-ActCode",
    "code": "VR",
    "display": "virtual"
  },
  "subject": {
    "reference": "Patient/example"
  }
}

### DELETE Encounter
DELETE {{fhirUrl}}/Encounter/{{postCompleteEncounter.response.body.$.id}}
Accept: {{format}}

### GET Encounter
GET {{fhirUrl}}/Encounter/{{postCompleteEncounter.response.body.$.id}}
Accept: {{format}}

### 
GET {{fhirUrl}}/Patient/d184bb4c-f02f-41e8-88d4-b7f461f1fe61
Accept: {{format}}
If-None-Match: W/"1"