// Configuration
# @fhirUrl = http://localhost:5826/fhir/smart
@fhirUrl = http://localhost:5826/fhir/open
# @fhirUrl = http://ecr.ri.argo.run/fhir/r4
#  @fhirUrl = https://vitals-server.ri.argo.run/fhir/smart

### GET Metadata
# @name fhirMetadata
GET {{fhirUrl}}/metadata
Accept: application/fhir+json

### GET SMART Well-Known
# @name smartWellKnown
GET {{fhirUrl}}/.well-known/smart-configuration
Accept: application/json

### Auth
# @name smartAuthorize
GET {{smartWellKnown.response.body.$.authorization_endpoint}}?response_type=code&client_id=fhir_demo_id&redirect_uri=http%3a%2f%2f127.0.0.1%3a65059&scope=openid+fhirUser+profile+launch%2fpatient+patient%2f*.read&state=local_state&aud={{fhirUrl}}
# GET http://localhost:5826/fhir/r4/authorize?response_type=code&client_id=fhir_demo_id&redirect_uri=http%3a%2f%2f127.0.0.1%3a65059&scope=openid+fhirUser+profile+launch%2fpatient+patient%2f*.read&state=local_state&aud=http://localhost:5826/fhir/r4/
Accept: application/json

###
GET {{fhirUrl}}/Patient/example
Authorization: Bearer 00000000-0000-0000-0000-000000000000_00000000-0000-0000-0000-000000000000

### PUT Patient
PUT {{fhirUrl}}/Patient/example
Accept: application/fhir+json
Content-Type: application/fhir+json

<@ ./patient-example.json


###
GET {{fhirUrl}}/Practitioner/davinci-susan-watson
Authorization: Bearer 882a562c-111c-44c8-b1e6-dc26643d0c7d_e4cd1eb7-6f1e-43a5-82c6-ebc41c073ebc

###
GET {{fhirUrl}}/Patient/example
Authorization: Bearer b413bbe7-823d-4423-ba31-be962158b705_4c1701e9-607e-41e6-88c9-066526d5650e

###
https://launch.smarthealthit.org/sample-app?aud=https%3A%2F%2Flaunch.smarthealthit.org%2Fv%2Fr4%2Fsim%2FWzMsIiIsIiIsIkFVVE8iLDAsMCwwLCIiLCIiLCIiLCIiLCIiLCIiLCIiLDAsMV0%2Ffhir
https://launch.smarthealthit.org/sample-app?aud=https%3A%2F%2Fvitals-server.ri.argo.run%2Ffhir%2Fsmart

abdedb37-d919-4df9-b468-ad046d9f35d7_8abf8c07-4148-43cb-9596-322d416ca3e6
11111111-1111-1111-1111-111111111111_11111111-1111-1111-1111-111111111111
00000000-0000-0000-0000-000000000000_00000000-0000-0000-0000-000000000000



#### Client Assertion for demo_app_whatever

POST {{smartWellKnown.response.body.$.token_endpoint}}
Accept: application/json
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&scope=system%2F*.rs&client_assertion_type=urn%3Aietf%3Aparams%3Aoauth%3Aclient-assertion-type%3Ajwt-bearer&client_assertion=eyJ0eXAiOiJKV1QiLCJraWQiOiJhZmIyN2MyODRmMmQ5Mzk1OWMxOGZhMDMyMGUzMjA2MCIsImFsZyI6IkVTMzg0In0.eyJpc3MiOiJkZW1vX2FwcF93aGF0ZXZlciIsInN1YiI6ImRlbW9fYXBwX3doYXRldmVyIiwiYXVkIjoiaHR0cHM6Ly9zbWFydC5hcmdvLnJ1bi92L3I0L3NpbS9leUp0SWpvaU1TSXNJbXNpT2lJeElpd2lhU0k2SWpFaUxDSnFJam9pTVNJc0ltSWlPaUk0TjJFek16bGtNQzA0WTJGbExUUXhPR1V0T0Rsak55MDROalV4WlRaaFlXSXpZellpZlEvYXV0aC90b2tlbiIsImp0aSI6ImQ4MDJiZDcyY2ZlYTA2MzVhM2EyN2IwODE3YjgxZTQxZTBmNzQzMzE4MTg4OTM4YjAxMmMyMDM2NmJkZmU4YTEiLCJleHAiOjE2MzM1MzIxMzR9.eHUtXmppOLIMAfBM4mFpcgJ90bDNYWQpkm7--yRS2LY5HoXwr3FpqHMTrjhK60r5kgYGFg6v9IQaUFKFpn1N2Eyty62JWxvGXRlgEDbdX9wAAr8TeWnsAT_2orfpn6wz


#### Client Assertion for demo_app_whatever

POST {{smartWellKnown.response.body.$.token_endpoint}}
Accept: application/json
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&scope=system%2F*.rs&client_assertion_type=urn%3Aietf%3Aparams%3Aoauth%3Aclient-assertion-type%3Ajwt-bearer&client_assertion=eyJ0eXAiOiJKV1QiLCJraWQiOiJhZmIyN2MyODRmMmQ5Mzk1OWMxOGZhMDMyMGUzMjA2MCIsImFsZyI6IkVTMzg0In0.eyJpc3MiOiJkZW1vX2FwcF93aGF0ZXZlciIsInN1YiI6ImRlbW9fYXBwX3doYXRldmVyIiwiYXVkIjoiaHR0cHM6Ly9zbWFydC5hcmdvLnJ1bi92L3I0L3NpbS9leUp0SWpvaU1TSXNJbXNpT2lJeElpd2lhU0k2SWpFaUxDSnFJam9pTVNJc0ltSWlPaUk0TjJFek16bGtNQzA0WTJGbExUUXhPR1V0T0Rsak55MDROalV4WlRaaFlXSXpZellpZlEvYXV0aC90b2tlbiIsImp0aSI6ImQ4MDJiZDcyY2ZlYTA2MzVhM2EyN2IwODE3YjgxZTQxZTBmNzQzMzE4MTg4OTM4YjAxMmMyMDM2NmJkZmU4YTEiLCJleHAiOjE2MzM1MzIxMzR9.eHUtXmppOLIMAfBM4mFpcgJ90bDNYWQpkm7--yRS2LY5HoXwr3FpqHMTrjhK60r5kgYGFg6v9IQaUFKFpn1N2Eyty62JWxvGXRlgEDbdX9wAAr8TeWnsAT_2orfpn6wz


#### Client Assertion for https://bili-monitor.example.com

POST {{smartWellKnown.response.body.$.token_endpoint}}
Accept: application/json
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&scope=system%2F*.rs&client_assertion_type=urn%3Aietf%3Aparams%3Aoauth%3Aclient-assertion-type%3Ajwt-bearer&client_assertion=eyJhbGciOiJSUzM4NCIsImtpZCI6ImVlZTlmMTdhM2I1OThmZDg2NDE3YTk4MGI1OTFmYmU2IiwidHlwIjoiSldUIn0.eyJpc3MiOiJodHRwczovL2JpbGktbW9uaXRvci5leGFtcGxlLmNvbSIsInN1YiI6Imh0dHBzOi8vYmlsaS1tb25pdG9yLmV4YW1wbGUuY29tIiwiYXVkIjoiaHR0cHM6Ly9hdXRob3JpemUuc21hcnRoZWFsdGhpdC5vcmcvdG9rZW4iLCJleHAiOjE0MjI1Njg4NjAsImp0aSI6InJhbmRvbS1ub24tcmV1c2FibGUtand0LWlkLTEyMyJ9.D5kAqNJwaftCqsRdVVQDq6dMBxuGFOF5svQJuXbcYp-oEyg5qOwK9ZE5cGLTHxqwfpUPNzRKgVdIGuhawAA-8g0s1nKQae8CuKs33hhKh4J34xSEwW3MYs1gwI4GHTtR_g3kYSX6QCi14Ed3GIAvYFgqRqt-gD7sewMUXL4SB8I8cXcDbCqVizm7uPVhjw6QaeKZygJJ_AVLhM4Xs9LTy4HAhdCHpN0FrNmCerUIYJvHDpcod7A0jDmxdoeW1KIBYlhdhQNwjtsTvT1ce4qacN_3KIv_fIzCKLIgDv9eWxkjAtxOmIm8aW5gX9xX7X0nbd0QglIyiic_bZVNNEh0kg