// Configuration
@candleUrl = http://localhost:5826/fhir/r4

@endpoint = http://localhost:5826/fhir/r4/$subscription-hook
@topic = http://hl7.org/fhir/us/core/SubscriptionTopic/patient-data-feed

# @contentLevel = empty
# @contentLevel = id-only
@contentLevel = full-resource

@format = application/fhir+json

### GET Metadata - candle
GET {{candleUrl}}/metadata
Accept: application/fhir+json

### POST Basic SubscriptionTopic URL Search Parameter
POST {{candleUrl}}/SearchParameter
Accept: application/fhir+json
Content-Type: application/fhir+json

<@ ./SearchParameter-basic-topic-url.json

### List subscription topics
GET {{candleUrl}}/Basic?code=http://hl7.org/fhir/fhir-types|SubscriptionTopic
Accept: application/fhir+json

### Resolve data-feed subscription topic
# @name resolveTopicDataFeed
GET {{candleUrl}}/Basic?subscriptiontopic-url=http://hl7.org/fhir/us/core/SubscriptionTopic/patient-data-feed
Accept: application/fhir+json

### Resolve a patient
# @name resolvePatient
GET {{candleUrl}}/Patient?_id=example
Accept: application/fhir+json

### POST Subscription
# @name postRestHookSubscription
POST {{candleUrl}}/Subscription
Accept: {{format}}
Content-Type: application/fhir+json

{
  "resourceType": "Subscription",
  "status": "requested",
  "reason": "Test subscription",
  "criteria": "{{topic}}",
  "_criteria" : {
    "extension": [
      {
        "url": "http://hl7.org/fhir/uv/subscriptions-backport/StructureDefinition/backport-filter-criteria",
        "valueString": "Patient/{{resolvePatient.response.body.$.entry[0].resource.id}}"
      }
    ]
  },
  "channel": {
      "extension": [
          {
              "url": "http://hl7.org/fhir/uv/subscriptions-backport/StructureDefinition/backport-heartbeat-period",
              "valueUnsignedInt": 86400
          },
          {
              "url": "http://hl7.org/fhir/uv/subscriptions-backport/StructureDefinition/backport-timeout",
              "valueUnsignedInt": 60
          },
          {
              "url": "http://hl7.org/fhir/uv/subscriptions-backport/StructureDefinition/backport-max-count",
              "valuePositiveInt": 20
          }
      ],
      "type": "rest-hook",
      "endpoint": "{{endpoint}}",
      "payload": "{{format}}",
      "_payload": {
          "extension": [
              {
                  "url": "http://hl7.org/fhir/uv/subscriptions-backport/StructureDefinition/backport-payload-content",
                  "valueCode": "{{contentLevel}}"
              }
          ]
      }
  }
}